import { useInfiniteQuery } from "@tanstack/react-query";
import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "../../components/Navbar";
import ProductGrid from "../../components/ProductGrid";
import Skelton from "../../components/Skelton";

const dummyCategory =  {
    name: "Category 1",
    products: [
        {
            id: 1,
            title: "Product 1",
            description: "Product 1 Description",
            price: 100,
            quantity: 10,
            image: "https://picsum.photos/200/300",
        },
        {
            id: 2,
            title: "Product 2",
            description: "Product 2 Description",
            price: 200,
            quantity: 20,
            image: "https://picsum.photos/200/300",
        },
    ],
    hasMore: false,
};

const SingleCategory = () => {
    const router = useRouter();

    const getSingleCategory = async ({ pageParam = null }) => {
        try {
            let url = `/api/categories/${router.query.id}`;
            if (pageParam) {
                url += `?cursorId=${pageParam}`;
            }
            const respJSON = await fetch(url);
            const resp = await respJSON.json();
            return resp;
        } catch (error) {
            console.error(error);
            throw error;
        }
    };

    const { isLoading, data, fetchNextPage } = useInfiniteQuery(
        {
            queryKey: [`singleCategory ${router.query.id as string}`],
            queryFn: getSingleCategory,
            enabled: !!router.query.id,
            getNextPageParam: (lastPage) => {
                const nextCursor =
                    lastPage?.category?.products[
                        lastPage?.category?.products?.length - 1
                    ]?.id;
                return nextCursor;
            },
            initialPageParam: null,
        }
        );

    const allProductsWithCategory: any = {
            name: "",
            products: [],
            hasMore: false,
    };

    data?.pages.map((page) => {
        if (page?.category) {
            if (page.category?.name) {
                allProductsWithCategory.name = page.category?.name;
            }
            if (page.category?.products && page.category?.products.length > 0) {
                allProductsWithCategory.products.push(
                    ...(page.category?.products ?? [])
                );
            }
        } else {
            allProductsWithCategory.name = dummyCategory.name;
            allProductsWithCategory.products.push(...dummyCategory.products);
        }
        return page?.category;
    });

    if (data?.pages[data?.pages.length - 1]?.category?.products.length === 0) {
        allProductsWithCategory.hasMore = false;
    }
    
    return (
        <div>
            <Head>
                <title>
                    {isLoading
                        ? "Loading..."
                        : `All ${allProductsWithCategory?.name} Product`}
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container mx-auto">
                <Navbar />
                {isLoading ? (
                    <Skelton />
                ) : (
                    <>
                        {allProductsWithCategory &&
                            allProductsWithCategory.products.length > 0 && (
                                <ProductGrid
                                    hasMore={allProductsWithCategory.hasMore}
                                    showLink={false}
                                    categories={[allProductsWithCategory]}
                                    loadMoreFun={fetchNextPage}
                                />
                            )}
                    </>
                )}
            </main>
        </div>
    );
};

export default SingleCategory;
